### ISSUE TITLE
Need a new release tag for Carthage and OS X

### ISSUE THREAD

**Issue by toadzky** [phimage/SLF4Swift#3]
The changes in https://github.com/phimage/SLF4Swift/pull/2 don't get found by Carthage since Carthage only finds release tags without a specific hash. Can we get a new release?

**Comment by phimage** [comment]
You can push a 2.0.2 tag now

Podpsec is already updated. Next week I will push to cocoapod

**Comment by toadzky** [comment]
2.0.2 released
