### ISSUE TITLE
Incorrect import on OSX framework

### ISSUE THREAD

**Issue by toadzky** [phimage/SLF4Swift#5]
@phimage I'm actually pretty new at Cocoa/Xcode etc, so I apparently did something wrong. It fails when I do 

```
...
import SLF4Swift
...
```

Instead, I have to 

```
...
import SLF4SwiftOSX
...
```

I've seen (and examined) other libraries that have the OS X build imported as the normal library name, but I can't for the life of me figure out how to do it.

I'm happy to fix it myself if you can point me in the right direction.

**Comment by phimage** [comment]
ok name is computed automatically from target name but you can edit it
go to built setting of target and change product name to SLF4Swift

**Comment by toadzky** [comment]
Thanks
